### ISSUE TITLE
Add Python Project - YouTube Music Downloader 

### ISSUE THREAD

**Issue by AkshatBhat** [Aniket11007/HacktoberFest2022-Newbie#19]
YouTube Music Downloader will download music from YT given the link, and save the mp3 file to your local desktop!

**Comment by Aniket11007** [comment]
go ahead bro and do checkout contribution guidelines

**Comment by AayushiSingh005** [comment]
Can you plz assign a issue to me?

**Comment by AayushiSingh005** [comment]
I have created the issue

**Comment by AkshatBhat** [comment]
Thanks for assigning the issue. Please merge the same. Also, some parts of contributing in README will have to be changed as the Branch method of contributing does not work due to the 403:UNAUTHORIZED error. Hence, only the Fork method of contributing will work. You can update the README with the steps for forking and then creating a pull request :)

**Comment by Aniket11007** [comment]
Sure @AkshatBhat
