### ISSUE TITLE
Unable to find contributors.md

### ISSUE THREAD

**Issue by webdemo07** [Aniket11007/HacktoberFest2022-Newbie#3]
Hey Aniket where is the file named CONTRIBUTORS.md?

![image](https://user-images.githubusercontent.com/98474970/193859086-62fe60e8-7cbb-4721-807e-b5b3b0a2f293.png)
  and where do we have to perform this task?

**Comment by Aniket11007** [comment]
Removing this section and kindly follow all the rules .
Happy contributing!
